### ISSUE TITLE
Editor not loading

### ISSUE THREAD

**Issue by Kjessall** [tinymce/tinymce-blazor#59]
As the title suggests I have an issue where sometimes the editor will not load, I have followed the example for setting up a blazor app to use the hosted version of the editor component.

I'm sure its me doing something wrong so any pointers would be helpful

This is how the editor is added to the page, like I say it works most of the time but on the initial load of the component it doesnt seems to.

`<TinyMCE.Blazor.Editor Conf="editorConf" @bind-Value="@Question.QuestionText" Field="() => Question.QuestionText" ApiKey="" />`

There are 2 messages in the console output

Uncaught TypeError: Cannot read properties of undefined (reading 'length')
    at tinymce.min.js:9:26875
    at HTMLLinkElement.h (tinymce.min.js:9:26961)

and

Uncaught TypeError: Cannot read properties of null (reading 'innerWidth')
    at jA.<anonymous> (theme.min.js:9:279034)
    at hA.dispatch (tinymce.min.js:9:372724)
    at jA.dispatch (tinymce.min.js:9:373978)
    at Array.<anonymous> (tinymce.min.js:9:400272)
    at Ne (tinymce.min.js:9:5303)
    at Object.KA (tinymce.min.js:9:400182)
    at ia.executeHandlers (tinymce.min.js:9:52234)
    at i (tinymce.min.js:9:50072)

**Comment by KoderK-Sharp** [comment]
Just a note, I have tried this both with the Conf supplied and excluded it happens in both cases.

**Comment by KoderK-Sharp** [comment]
Anyone?

**Comment by jscasca** [comment]
If it only happens sometimes it must be a race condition that is bound by load times. It would be hard to tell only providing the editor line of code. There must be something else in the page messing up the loadout. Do you have a reproduction by any chance? Happy to help

**Comment by collinsmarra** [comment]
I'm also running into the same problem with .NET 8, but only on the initial load.

**Comment by Wilock1** [comment]
I'm having the same issue in my blazor web app on initial page load. All I see is a textarea control. Once I refresh the page it works fine. I've seen this issue reported a lot with many good suggestions including putting "await JSRuntime.InvokeVoidAsync("tinymce.init", new object[] { });" in the "protected override async Task OnAfterRenderAsync(bool firstRender)". However, because TinyMCE is installed via Nuget there is no direct access to the javascript (or at least I don't know how to do it).

**Comment by boomalator** [comment]
> However, because TinyMCE is installed via Nuget there is no direct access to the javascript (or at least I don't know how to do it).

This worked for me: https://github.com/tinymce/tinymce-blazor/issues/89#issuecomment-3301066439

**Comment by tiny-ben-tran** [comment]
@KoderK-Sharp have you managed to resolve your issue?
